### ISSUE TITLE
Add a button to switch home page from active to finished auctions.

### ISSUE THREAD

**Issue by PopcornPaws** [agoraxyz/gold.xyz#60]
## Description
Auctions are now split into two pools. In the primary pool (the one used so far) we have all the active auctions that are currently accepting bids. In the secondary pool we have the finished (and/or filtered) auctions. If someone wants to check a finished auction they will have to press a button (or something) to switch to another page which will start listing finished auctions.

Reason behind this is that we want to avoid querying finished auctions on the home page as it is quite slow.

In the contract logic, we'll need to add a flag to the `getAuctions` function that determines which pool we are querying.

**Comment by dovalid** [comment]
Done in 8afd0340063d3a59b8f2eae1393950e52c44d5f9
